### ISSUE TITLE
Where is the custom poco?

### ISSUE THREAD

**Issue by trippleflux** [ArmaLife/extDB2#1]
It seems https://github.com/Torndeco/poco already removed, could you please upload custom poco for extdb2 v71?

**Comment by danielstuart14** [comment]
https://github.com/danielstuart14/extDB2

I didn't try it yet, so, idk if it works.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/extDB2

**Comment by trippleflux** [comment]
Confirmed compilable with long and exhausted way to compile it but not tested it yet on live server. Why you are deleting poco repo?

**Comment by danielstuart14** [comment]
I wasn't being able to compile it...

Here, you can found: https://github.com/danielstuart14/poco/tree/poco-1.7.3

**Comment by trippleflux** [comment]
You need to use poco specifically v1.6.1-all, extract to a dir and replace it with the contents from poco-changes.
